dist: trusty
sudo: required
language: bash
env:
  - ansible_version=2.7.1
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2018-11/run.sh |
  bash
- sudo apt-get update -qq
install:
  - sudo apt-get install -y unzip wget
  - sudo pip install --upgrade pip
  - sudo pip install ansible==${ansible_version}
  - sudo pip install ansible-lint
  - wget -O packer.zip https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip
  - sudo unzip -o packer.zip -d /usr/local/bin
  - wget -O terraform.zip https://releases.hashicorp.com/terraform/0.11.9/terraform_0.11.9_linux_amd64.zip
  - sudo unzip -o terraform.zip -d /usr/bin/
  - wget -O tflint.zip https://github.com/wata727/tflint/releases/download/v0.7.4/tflint_linux_amd64.zip
  - sudo unzip -o tflint.zip -d /usr/bin/
  - cd terraform/stage
  - cp terraform.tfvars.example terraform.tfvars
  - cd ../prod
  - cp terraform.tfvars.example terraform.tfvars
  - touch ~/.ssh/appuser.pub
  - cd ../../
script:
  - packer validate -var-file=packer/variables.json.example packer/app.json
  - packer validate -var-file=packer/variables.json.example packer/db.json
  - cd terraform/stage
  - terraform init -backend=false && terraform validate && tflint
notifications:
  slack:
    rooms:
      secure: im6yxhhcVaHiPNY5OwicnRnPjC1qlmzzWiVYfU+gONItQznpDZ/+bcsC5NsgmoQzVfPYnxKtW538C3kr+hEYFsu4qWnHv/wnTFX7OKlswLGcz5bwoifoo7uxfn6dbhBt6fRQfDnRrgtp+scSQ+cPmz/cgk7aaDhodc3Q+IllwKrf0r8u0M7XiJg2dl4oBLOe20HhQesauH+hAmp9jWbgc27bLAbhxE7HcxYtsctb6Q9m7jNWRIidLIlOwcHZmgfgDu3Zp73W04cC6Z118fmlNWOtKnGla2e3CFb0ePc4QVUish7sLvqeQyBi5ooTQzy4eufzkcnpQX4KWF4XLGFlrhiwwnuxhr3TLxkL47RJdxa19znpc9/kQjkUUtmsF6RAIUUnvsyHrxigFg25cu5FH6MAvQ2kTq9tuF+FDUprN/c5NgZNshLALG4GDYg7tzJDP+5Sa9+qJ9vuvqI2Q0Oa+OUvnUgH1Bco1SUrtVmS7+7O3LY9d8u7gIYtFF5RkGBBianCrOL23DuDETZBJojq3od2vi979NlYgrRgoLYKpCrm2p9zsRLoGPAoPiqlVwoUnvjpmck1AcrIL5skz0Oix/j6Om9O98mKmB5JtSzfM10X9vqHCTPr6PUdhqPwpIEY/ZB9O5qY7Ki77DbR0P3nVV2rqABbGxdpd1o8sUP9/60=
